CREATE TABLE department_details
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR(255),
    department_address VARCHAR(255),
    department_code VARCHAR(255),
    PRIMARY KEY (id)
);
